### ISSUE TITLE
Ambiguity in symbol's units

### ISSUE THREAD

**Issue by shinsid** [XingzhiMac/CAS741-Proj#10]
![Screenshot from 2020-10-17 14-35-05](https://user-images.githubusercontent.com/12082585/96350895-f8745380-1085-11eb-8f6c-3bbc1d3a7b08.png)

The units for the above symbols are not very clear to me.

**Comment by XingzhiMac** [comment]
Ahh I made a mistake here. The unit at the first line should definitely be dBm. Thanks very much!

**Comment by XingzhiMac** [comment]
@shinsid I pushed commit 2620e869943281d37fc192ea1ad28b35b1d352b4 for this issue.
