### ISSUE TITLE
Possibility of a typo

### ISSUE THREAD

**Issue by shinsid** [XingzhiMac/CAS741-Proj#11]
![Screenshot from 2020-10-17 14-37-08](https://user-images.githubusercontent.com/12082585/96350927-4426fd00-1086-11eb-86e9-e359c91c01b1.png)

Is 'x' at the end of symbol a typo?

**Comment by XingzhiMac** [comment]
@shinsid Thanks for pointing out that typo. I pushed commit 2aa972056c12f57c940dac30dda5f999742e193f for it.
