### ISSUE TITLE
Possible typo in SystemContext 

### ISSUE THREAD

**Issue by shinsid** [XingzhiMac/CAS741-Proj#13]
![Screenshot from 2020-10-17 14-40-03](https://user-images.githubusercontent.com/12082585/96350988-ab44b180-1086-11eb-942c-5af92b6c357b.png)

Should RSC be RSSC?

**Comment by smiths** [comment]
@XingzhiMac if closing this issue involves pushing a new commit, please include the commit hash as part of your message when closing the issue.

**Comment by XingzhiMac** [comment]
@smiths @shinsid I pushed commit 64b2d0591abf448a434932973f8f0aa39e7b839d for this issue.
