### ISSUE TITLE
Table 5 is out of page bounds

### ISSUE THREAD

**Issue by shinsid** [XingzhiMac/CAS741-Proj#15]
Table 5: Traceability matrix is exceeding page limits. You can try fitting it in a landscape page.

Also in the text below the table the figure references are missing.

**Comment by XingzhiMac** [comment]
I pushed 89350d2ed0046f651d9734248a1de6a76fa79f21 and a385def4da0334b893f5afd4187fb8a6c6f2b97d for this issue.  
I also uploaded the pdf file for the Revised SRS.
