### ISSUE TITLE
Question in derviation of n

### ISSUE THREAD

**Issue by shinsid** [XingzhiMac/CAS741-Proj#16]
![Screenshot from 2020-10-19 17-31-41](https://user-images.githubusercontent.com/12082585/96513988-04e8df80-1231-11eb-8ea8-5e52b0cf3f7c.png)

This could be a silly question but I did not understand it very well.

I did not understand how [(x_D_x - x_C_x) (y_D_x - y_C_x)] becomes [A B].

**Comment by XingzhiMac** [comment]
That's because I defined A and B as (x_D_x - x_C_x) and (y_D_x - y_C_x) respectively at the beginning of the equation derivation.
![image](https://user-images.githubusercontent.com/70971553/97641657-c82f9c00-1a19-11eb-9153-c302c190548a.png)

**Comment by shinsid** [comment]
Ohh, somehow I completely missed it. Thanks for the clarification! :+1:
