### ISSUE TITLE
VnV: underdeveloped automated testing and verification tools

### ISSUE THREAD

**Issue by shmouses** [XingzhiMac/CAS741-Proj#20]
Dear Xingzhi, 
I post this issue to function more like a reminder for completing the automated testing section. I believe this section can use a little bit of more description such as which test cases are covered by automated testing how you are implementing. But like other issues it is just a friendly suggestion. 

![image](https://user-images.githubusercontent.com/49411064/98455951-27da2580-2145-11eb-81a1-5bc35af5a5f6.png)

**Comment by XingzhiMac** [comment]
Thanks for your comment! I added more content in (98a2667).
