### ISSUE TITLE
VnV: Conclusion

### ISSUE THREAD

**Issue by shmouses** [XingzhiMac/CAS741-Proj#21]
Dear Xiangzhi, 
My review of the VnV document is done. I found your test cases sufficient in terms of giving a specificity of what is the input to the system and what output is expected. However, on the plans side, I believe they can be more specific, and VnV members can be assigned specific tasks.  
Good luck!

**Comment by XingzhiMac** [comment]
Hi Shayan, thanks very much for your comment! I have pushed a new version of VnV to the repo.
