### ISSUE TITLE
SRS Does Not Compile

### ISSUE THREAD

**Issue by smiths** [XingzhiMac/CAS741-Proj#22]
The `SRS.tex` file does not compile, at least in part because `floorPlan` is not under version control.  There is also code in the SRS file that look to be left over from a merge conflict, like on line 1636.

I also pushed a version (28222d9) with a few spelling mistakes corrected.

**Comment by XingzhiMac** [comment]
I addressed the issue in ( 7145beb ).  Thanks for the comment!
