### ISSUE TITLE
MG + MIS ready to review

### ISSUE THREAD

**Issue by XingzhiMac** [XingzhiMac/CAS741-Proj#24]
Hi Sid @shinsid ,

I would like to invite you to review my MG and MIS at https://github.com/XingzhiMac/CAS741-Proj/tree/master/docs/Design.

Thanks!

Xingzhi

**Comment by shinsid** [comment]
Hi @XingzhiMac ,

Sorry for the late response. I am starting to review your documents now and shall finish by end of today.

Thanks,
Sid

**Comment by XingzhiMac** [comment]
Thank you!

Xingzhi
