### ISSUE TITLE
MG - Reference to your SRS document is missing 

### ISSUE THREAD

**Issue by shinsid** [XingzhiMac/CAS741-Proj#27]
The reference to your SRS document is missing in your Module Guide.

**Comment by XingzhiMac** [comment]
Hi Sid,

Thanks for your comment.  I'm sorry that I don't know how to fix it because I cannot reproduce this issue. I will upload a new pdf file anyway if that problem still happens to you.

**Comment by XingzhiMac** [comment]
The pdf file has been uploaded in (d609ef4).
