### ISSUE TITLE
MG - Question in Software Decision Modules section

### ISSUE THREAD

**Issue by shinsid** [XingzhiMac/CAS741-Proj#29]
After reading the details about the software decision modules, I felt that some of these modules (e.g. Wall, Point, etc) that are data structures in your program should belong to the Behavior Hiding category.

This is my understanding but I could be wrong here.

![image](https://user-images.githubusercontent.com/12082585/100533972-614c0100-31d8-11eb-9635-e1aeab557820.png)

**Comment by XingzhiMac** [comment]
Hi Sid, 

Thanks for your comment!

I referred to the SWHS example (https://github.com/smiths/swhs/blob/master/docs/Design/MG/PCM_MG.pdf) when I was composing this part, and the data structures of walls, points, linear paths, etc. in RSSC are similar to the sequence data structure module in SWHS which belongs to the Software Decision Module.

The reason I put them under the Software Decision Module is that the user has nothing to do with these data structures in my plan. Instead, the user only provides some coordinates and parameters to RSSC, and receives an output file. The data structures like points, walls, etc. are created just for the convenience of calculation, and not accessible by the user, and hence they are equivalent to the sequence data structure module in SWHS and should be put under Software Decision Module.
