### ISSUE TITLE
Symbols/Abbreviations in MIS

### ISSUE THREAD

**Issue by muralidn** [XingzhiMac/CAS741-Proj#31]
@XingzhiMac 

There is no abbreviations/symbols table in the MIS. Are there no additional symbols in the MIS apart from those already recorded in SRS? Can the logic symbols such as  ∀ (forall) considered to be common knowledge?

**Comment by XingzhiMac** [comment]
Thanks for your comment! In SRS I mentioned that the intended readers are supposed to complete Engineering mathematics level 2 and familiar with its topics. The symbols like (forall), (not), or (implies) are frequently used in formula derivation and verification in textbooks of courses like Engineering 1ZB3, and 1ZC3, which are under the categories of level 2 Engineering Mathematics, so I assumed that it was common knowledge among intended readers.
I added those symbols and their descriptions in (85cb87b) anyway.
