### ISSUE TITLE
AC2 is too abstract

### ISSUE THREAD

**Issue by muralidn** [XingzhiMac/CAS741-Proj#33]
@XingzhiMac 

AC2 sounds too abstract. I believe more details such as how the control of the calculation changes is necessary.

![image](https://user-images.githubusercontent.com/71282513/100935431-1999e200-3516-11eb-9800-002277251e90.png)

**Comment by XingzhiMac** [comment]
Thanks for your comment. The issue has been addressed in (d609ef4).
