### ISSUE TITLE
MG and MIS

### ISSUE THREAD

**Issue by JohnErnsthausen** [XingzhiMac/CAS741-Proj#35]
Hello, Xingzhi @XingzhiMac and Prof. Smith @smiths. My MG and MIS documents are ready for review.

I struggled with these documents. I'm not sure I have it right yet. There was a need to add requirements. I started updating my SRS.

**Comment by smiths** [comment]
@JohnErnsthausen, you should create the issue for reviewing your repo IN your repo, not in Xingzhi's repo.  :smile:
