### ISSUE TITLE
The ProgName should be replaced in Common.tex

### ISSUE THREAD

**Issue by shinsid** [XingzhiMac/CAS741-Proj#6]
Hi Xingzhi,

I started reviewing your SRS document yesterday, however, it is not finished yet. Your SRS document is a bit lengthy and also I do not have the required technical background so it is taking some time. But I have started creating issues so you can start working on it.

Issue# 1 - 
![Screenshot from 2020-10-17 14-21-37](https://user-images.githubusercontent.com/12082585/96350504-1640b900-1084-11eb-9a17-c90693cfec57.png)

The ProgName should be replaced in Common.tex

**Comment by XingzhiMac** [comment]
Thanks. I will change it in the next revision.

**Comment by XingzhiMac** [comment]
I pushed commit 5a2b4134c6db3ec026438bfa1c21f6fda20938ad for this issue.
