### ISSUE TITLE
Statement should be adapted with your project

### ISSUE THREAD

**Issue by shinsid** [XingzhiMac/CAS741-Proj#8]
![Screenshot from 2020-10-17 14-27-59](https://user-images.githubusercontent.com/12082585/96350718-f9f14c00-1084-11eb-8b4a-ad310e1458c0.png)

Suggestion - I believe this statement should be adapted to your project. According to my understanding, the reader of this document might not know anything about SWHS.

**Comment by XingzhiMac** [comment]
I can't believe I made such a terrible mistake. Thanks so much for letting me know this!

**Comment by XingzhiMac** [comment]
I pushed commit fe5f835a83dfd844a979f85c2e5fd70b444ad0ef for this issue.
